[package]
name = "json-array-test"
version = "0.1.0"
edition = "2021"

[dependencies]
json-array-derive = { path = "../json-array-derive" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
